### ISSUE TITLE
Support For Systemd's Journal

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#218]
VLC 2.3.0 (git) just gained support for this : http://www.phoronix.com/scan.php?page=news_item&px=VLC-Systemd-Journald-Logger
@xylosper : do u think there is any point to add this to bomi also?

**Comment by xylosper** [comment]
possible but how is this useful?

**Comment by M4rtinK** [comment]
Just from top of my head:
* single place to look for log output
* no need to handle log file creation/rotation/collisions/running out of space
 * just send it to the Journal interface and let it handle the rest
* the Journal API supports priorities and other metadata
 * users can see right away which messages are critical/non critical due to the build in journalctl message highlighting
* powerful filtering & cross reference
 * users can filter out just the bomi log output or check what happened at the same time as the bomi message was logged (bomi error accompanied by a x server error, etc.)
* powerful time based lookup - users can check all bomi log messages from last run, last day, last hour, etc.

More Journal resources:
http://www.freedesktop.org/software/systemd/man/journalctl.html
http://0pointer.de/blog/projects/journal-submit.html

**Comment by xylosper** [comment]
@M4rtinK 
If I implemeted this, do I still need to print logs to stdout?

**Comment by M4rtinK** [comment]
It depends - I guess most people should have Journald running nowadays. Also people might not want to have the terminal spammed when launching bomi ?
Maybe just print "bomi is logging to Journal" to stdout normally and only print all log messages to stdout it some environmental variable (say BOMI_DEBUG) is set ?

**Comment by xylosper** [comment]
I'm working next:

* add options to select logging level or turn it off for stdout, stderr, journal and external file
* if command line option `--log-level` is given, this will override logging level for stdout only

By default, bomi will log with journal only.
stdout/stderr is disabled by default because bomi is GUI application and usually, it will be launched without terminal screen which results into discarding all stdout/stderr outputs.

Also, if someone gave a command line option, it means he or she executed bomi from terminal, so I think it makes sense that --log-level affects stdout only.
Since this option already exists, I don't think additional env. var. is needed.

What I'm still concerning is default logging level(verbosity).
In fact, because of my lazyness, bomi doesn't log so much things yet but lots of messages are retrived from mpv.
In previous version, default level was 'info' because 'debug' was too noisy.
But if I can believe journald is fast enough, I want to raise the default logging level for journal to 'debug' because 'debug' can show much more information on crash.

If you have any suggetion about this, please let me know.

**Comment by M4rtinK** [comment]
Sounds good! :)

**Comment by ahjolinna** [comment]
@xylosper : one question about pkgbuild, is options=(debug !strip) need after this systemd support.
PS. bomi. is now add to chakraOS repos, and maybe become the default kf5 videoplayer.

**Comment by xylosper** [comment]
`options=(debug !strip) ` is irrelavant with systemd. It's debugging purpose options.

> PS. bomi. is now add to chakraOS repos, and maybe become the default kf5 videoplayer.

Great news. Can I see any related webpage? I want to post a link in twitter.

**Comment by ahjolinna** [comment]
@xylosper : there is only a forum post: http://chakraos.org/forum/viewtopic.php?pid=84929#p84929

**Comment by ahjolinna** [comment]
@xylosper : btw. NICE...VPDAU got HEVC (10bit-12-bit) support http://cgit.freedesktop.org/~aplattner/libvdpau/commit/?id=c199b6107fda78cc575f0bdace6327e85add7fa9&utm_source=anzwix
GTX 900 series graphics cards are needed for handling hardware-accelerated H.265 video decoding.

**Comment by ahjolinna** [comment]
@xylosper : bomi git does not build https://paste.kde.org/ptcyebccz

**Comment by xylosper** [comment]
You need to add `qt5-tools` to makedepends if Chakra's package has same name with that of Arch Linux.

**Comment by ahjolinna** [comment]
@xylosper : yeah that helped, thanks..btw. shouldn't systemd be added (okay its default almost everywhere, so maybe not)

**Comment by xylosper** [comment]
without systemd, the OS doesn't work. 

Anyway close this.
