### ISSUE TITLE
Build with external libmpv library

### ISSUE THREAD

**Issue by xmikos** [xylosper/bomi#239]
Please can you allow building Bomi with external mpv? Mpv provides shared _libmpv.so_ library that you can use. Bomi looks great, but I really don't want to have mpv multiple times in my system (and I don't want to unnecessarily rebuild internal mpv every time I am building Bomi). I am now forced to use [Baka MPlayer] (http://bakamplayer.u8sand.net) which supports external libmpv and is also Qt5 based, but Bomi looks like better GUI. But before it allows using external libmpv, it is not an option for me :-(

Support for shared libmpv library will also help adoption of Bomi in Linux distributions (inclusion in package repositories).

**Comment by xylosper** [comment]
Not possible.

**Comment by xmikos** [comment]
Why not? If it is possible for Baka MPlayer, why not for Bomi? libmpv library is there...

**Comment by xylosper** [comment]
Because bomi is not Baka MPlayer. It's totally different thing.
bomi cannot be separated from internal 'forked mpv'. It's not vanilla.

**Comment by xmikos** [comment]
Can't you cooperate with upstream mpv developers to have patches you need for Bomi incorporated in their codebase?

**Comment by xylosper** [comment]
I'm always doing it but that's not enough.
They don't allow customized vo/vf/af and this is not allowed in libmpv very first time.
These are based on C++ and cannot be just ported to mpv because their purpose is only for providing better integration with bomi.
Also, sometimes, something which I think a bug which I can fix is not considered as a bug by them.
In that case, I can just made a patch for internal mpv. (Sometimes, they're adopted by mpv through my pull request but it'll take some time.)
Futhermore, bomi seriously depends on (latest) mpv version, for instance such a case in above.
Even if libmpv is perfectly compatible with bomi, such a distro like Ubuntu whose packages are out-of-time soon after release cannot provide updated bomi.
I really have to write a wiki about this. Just one thing you have to know is the current position of bomi. bomi is not a front end of mpv. It's more like a fork of mpv.

**Comment by xmikos** [comment]
Ok, thank you for clarification.

**Comment by xylosper** [comment]
I wrote an article about this. If you are interested, please read [wiki](https://github.com/xylosper/bomi/wiki/bomi-is-not-a-front-end)
