### ISSUE TITLE
Request of Rpm package (Fedora)

### ISSUE THREAD

**Issue by ahloiscreamo** [xylosper/bomi#249]
i would like to request for rpm package.i try to compile if but a lot of dependencies package missing.Thanks in advance!

**Comment by breed808** [comment]
Hi, please see https://breed808.com/bomi/ for prebuilt Fedora packages. Fedora 21 has the latest packages built, while Fedora 20 is a bit out of date due to build issues.

**Comment by xylosper** [comment]
@ahloiscreamo 
I can help you to compile but I cannot provide new package because I don't have resources except Arch and Ubuntu.
I can provide Arch package because I'm using it.
Ubuntu is a special case because it provides PPA service.
All other packages are provided by users or disro's contribution.

@breed808 
What kind of build issue do you have?
I've just released 0.9.3 and I think the main restriction came from,
g++ >= 4.9, Qt >= 5.2, ffmpeg >= 2.4, libass >= 0.12
The latters are essential but g++ >= 4.9 may be replaced with clang(configure with --cc=clang)
If you have other issues, please ask me.

Btw, may I add your repo to download list in website?
Also, I can see the path named 'cmplayer-repo'. Is this for compatibility?

**Comment by ahloiscreamo** [comment]
@xylosper @breed808 guys thanks.I just installed it via repo for fedora 21.work like charm.!

**Comment by breed808** [comment]
@xylosper 
I'll have to double-check the build issues for Fedora 20, I'll let you know about them once I build 0.9.3.
As for the repo, yes, you're fine to add that to the website download list. The 'cmplayer-repo' path is for compatibility, but I can change this if it would be preferable.

**Comment by breed808** [comment]
As for the Fedora 20 packages, it would seem that I would need to update, build and host packages for ffmpeg and QT, which I feel would be too much effort to support an older version of Fedora.

I've updated and built libass in order for the Fedora 21 package to build, and that should be hosted on my server shortly.

**Comment by xylosper** [comment]
@breed808 
Thank you for your contribution. I've just updated download page.
Btw, bomi is now included in packman repo, which maybe you've already noticed.
So if maintaining/providing openSUSE package is a burden for you, you can just drop it.
