### ISSUE TITLE
"Handle as playlist" is broken

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/bomi#258]
It seems that "Handle as playlist" option is not working correctly if there is some parameters (with & and ? symbols) in URL. It doesn't add items from playlist URL to bomi playlist.

**Comment by Kosava** [comment]
Also related to playlist and subtitlefinder, when next video starts and when i want to search subtitle in subtitle finder, subtitle not fetch any subtitle it come to 50%, solution was to turn of bomi and again fetch subitles and apear, this problem is not constant it, sometimes come sometimes not, but in most cases there is nothing fetching for next video.

**Comment by ValdikSS** [comment]
Updated

**Comment by xylosper** [comment]
@ValdikSS 
Can I get a sample URL?

**Comment by ValdikSS** [comment]
@xylosper 
http://tv-msk.valdikss.org.ru:8000/torrent-telik/?type=allfon/playlist.m3u

**Comment by xylosper** [comment]
Fixed. Thank you.

@Kosava  It's unrelated issue with this. Please open other issue.

**Comment by ValdikSS** [comment]
Thanks a lot!
Please take a look at issue #7.
