### ISSUE TITLE
Issues with new audio normalizer

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/bomi#269]
Audio is usually out of sync or just doesn't play with new audio normalizer when the video is played not at 100% speed.
Audio is tempo scaled even with tempo scaling disabled.
Video is sought back (to the nearest I frame i believe) when you change any audio settings.

**Comment by xylosper** [comment]
> Audio is usually out of sync or just doesn't play with new audio normalizer when the video is played not at 100% speed.

Fixed.

> Audio is tempo scaled even with tempo scaling disabled.

Fixed.

> Video is sought back (to the nearest I frame i believe) when you change any audio settings.

Here's a thing. A real normalizer needs to know all audio data at once and then it calculated normalized level. However, it's not possible in real time of course.

Previous normalizer is in fact, a dynamico range compressor rather than a normalizer because I sees current audio buffer only.

New normalizer is a 'psuedo' normalizer which looks future and past  audio data with given interval. For this, it requires quite a long audio delay internally. Of course, this delay gets aways as soon as bufferred audiod data processed.

In most cases, a delay introduced by a audio filter is subseconds and it will go away almost instantaneously.
But new normalizer requires huge delay, for instance, by default it introduces about 15 seconds and it will take several seconds till the delay disappears. Also, this normalizer affects all other filters related with playback speed such as tempo scaler.

So, I added an 'resync' of A/V whever related parts are changed(normalizer, tempo scaler, playback speed) and the method to resync A/V is to enforce a seek.
That's why it seeks back to nearest key frame as you said.

I think one may think this is annoying so, I just added an option for this: 'Resynchronize audio/video when filter toggled'.
If you're willing to take the delay instead of seeking back, please turn the option off.
In that case, you may want to decrease 'Chunk length' and 'Smoothing filter radius' to reduce delay. Of course, this will make the normalizer less close to real normalizer.

Thank you.

**Comment by ValdikSS** [comment]
Thanks a lot!

**Comment by ValdikSS** [comment]
Sadly, audio desync issue is still present.

**Comment by xylosper** [comment]
What's the value of 'Audio/Video Sync' in playback information?

**Comment by ValdikSS** [comment]
Only milliseconds, but it's clearly delay for seconds.
1) Open any videofile in bomi
2) Set playback speed to 200%
3) Turn on volume normalizer

Result: audio is advancing video

4) Turn off volume normalizer

Result: audio and video is synced.

**Comment by xylosper** [comment]
Sorry, the fix wasn't applied.  Please try again.

**Comment by ValdikSS** [comment]
Nothing changed.

**Comment by ValdikSS** [comment]
It's fixed now, thanks!
