### ISSUE TITLE
make libvdpau+libbluray optional

### ISSUE THREAD

**Issue by ff2000** [xylosper/bomi#273]
I do not have the hardware (running intel laptop with simple DVD drive), so I don't need it.
I am sure there are other users like me who would appreciate such a change.

**Comment by xylosper** [comment]
They don't require actual hardware.
Anyway, I can disable vdpau/vaapi repectively.
However, it's not easy to disable libblurary because related parts are not maintained in separated code.
Futhermore, it's still valid for who have no BD drive because libbluray can play not only physical discs but also copied/mounted directory (and not-mounted ISO support is planned AFAIK).

**Comment by ff2000** [comment]
Yes, adding an option for vdpau definitely would be great. mpv itself offers quite some build time options, but I do not expect bomi to map them all.

BTW.: Why don't you simply integrate into mpv's build system (waf)? IMHO that should make tracking build flags etc. easier.

**Comment by xylosper** [comment]
> Why don't you simply integrate into mpv's build system (waf)?

Because it's controlled by mpv. I don't want to let it do instead of me.

**Comment by xylosper** [comment]
--disable-vaapi and --disable-vdpau options have been added. If you have still issue, please let me know. Thank you.
