### ISSUE TITLE
Display title instead url in history for video from streaming site.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#285]
Not an issue but a feature request. I played a video from a streaming site bomi display the video name in the windows title. But in the history it display the video url I think it will be more informative to the user to also display the video title in the history menu.

**Comment by xylosper** [comment]
There's a dilemma about this.

In fact, I had thought samething before but soon, I noticed that there are too many wrong-titled media including both of local file and streaming site.

It's not a problem that title does not exist, because in that case, I can fallback to display URL or file name.

However, once title is set regardless of its informativity, I enforced to display it even though the title is dummy because there's no way to tell an 'informative title' from 'bad title'.

Do you have any idea to resolve this problem?

**Comment by dragons4life** [comment]
IMO makes more sense to have the tittle/name instead of the ip/url. However why not just make it an option?

**Comment by mac1202** [comment]
IMHO the best think is to add 2 drop down menu option in misc > history view
something like
history mode for local video : -title
                                            -filename
                                            -full path + filename
history mode for streaming video : -title
                                                    -url

**Comment by xylosper** [comment]
Done. Thank you.
