### ISSUE TITLE
standalone installer for windows version

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#297]
I think a standalone installer would be good for windows users (and maybe mac someday). I think the current .zip version is little bit impractical + it's not so end user friendly. I recommend the Qt Installer Framework it support updating and online installation.... it was just ported to Qt5, it requires Qt 5.4 as a minimal version.

I have no idea if there is any point to make a Linux version.

http://wiki.qt.io/Qt-Installer-Framework
https://blog.qt.io/blog/2015/04/07/qt-installer-framework-2-0-released/

**Comment by xylosper** [comment]
> I think a standalone installer would be good for windows users (and maybe mac someday). 

Agree except mac part(you'd know that installer for mac is totally pointless if you'd ever used mac).

> I recommend the Qt Installer Framework it support updating and online installation.... it was just ported to Qt5, it requires Qt 5.4 as a minimal version.

An application never depends on its installer.
There's no point to use Qt-based installer for Qt application.
Also, without maintainment of repository, any features related with online state are meaningless.

> I have no idea if there is any point to make a Linux version.

It is not possible to make general purpose installer for Linux because there are too many different envs. Also, an installer would be never preferred to native package system for that distro.

The most important part of installer which I care is the binary size.
Without compression, bomi requires about 40MB.
With zip compression which is current deployment, the size of zip archive is about < 20MB.

In fact, there are only a few choices for installer which I can choose: NSIS, InnoSetup and Qt installer.
I'm looking for a comparison or binary size overhead for thouse installers but I couldn't yet.

**Comment by xylosper** [comment]
Installer for windows is uploaded: http://bomi-player.github.io/downloads.html#downloads-windows
