### ISSUE TITLE
Visually show the part of video that is cached on the progress bar.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#300]
I would be nice to display on the progress bar the part of the video that is cached. Something like what is done on the youtube player ([screenshot](http://i.imgur.com/oLHnpti.png))
PS : the new history/playlist design is gorgeous !

**Comment by xylosper** [comment]
I'm not sure that this is possible technically or not.
Since I'm preparing new version release, I'll check it later.

**Comment by xylosper** [comment]
I've done this but here are some notes:

* It's implemented in Tethy, Ardis, metro, and GaN only for now.
* When you saying cache, it may point two different things. One is total filled cache buffer in stream and other one is prefetched packets in demuxer. When data is in buffer of stream, you can't display the 'time' because the data is not parsed yet. So, what is displayed on seek bar is data only in demuxer not total cache.
