### ISSUE TITLE
Clean start window with empty title

### ISSUE THREAD

**Issue by famo** [xylosper/bomi#381]
I'm always annoyed by the fact that when you start bomi, that you have an empty window but something in the title. This gives a broken look, IMHO...
Also if one really wants to play his last video, there is always the playback history just one click away.

Furthermore if you have an (really) empty window, you can do cool thing like:
- Open File on play (VLC has this nice feature that you can push the play button in an empty video and it opens the Open Dialog).
- Or implement an dashboard

**Comment by xylosper** [comment]
> This gives a broken look, IMHO...

No it doesn't because it would be played when you start playback.
As you can see from various places in bomi, bomi puts emphasis on continuity of playback.

> Also if one really wants to play his last video, there is always the playback history just one click away.

This doesn't make any sense.
I can say 'if one really wants to play new file, there is always menu/shorcut to do that', too.

> implement an dashboard

This is much more insteresting but it requires lots of skill for design. It's very easy to implement once design is determined but my design skill is suck.
So, for now, I've imeplemented an option to load previous media on execution(youc an find it preferences > application).
It's turned on by default so if you don't like the behavior, please uncheck it.
Also now bomi will try to open file when no media loaded.

**Comment by famo** [comment]
So it's a new option (can't find it here now)?

Thats fine for me, thanks!
